// <auto-generated />
using IMS_Microservices.Services.MenuAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMS_Microservices.Services.MenuAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IMS_Microservices.Services.MenuAPI.Models.IMSMenu", b =>
                {
                    b.Property<int>("menuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("menuID"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("manuName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.HasKey("menuID");

                    b.ToTable("IMSMenus");

                    b.HasData(
                        new
                        {
                            menuID = 1,
                            category = "rice",
                            manuName = "Chicken Biriyani",
                            price = 10.0
                        },
                        new
                        {
                            menuID = 2,
                            category = "rice",
                            manuName = "Beef Biriyani",
                            price = 12.0
                        },
                        new
                        {
                            menuID = 3,
                            category = "drink",
                            manuName = "Teo Lemao",
                            price = 3.0
                        },
                        new
                        {
                            menuID = 4,
                            category = "side dish",
                            manuName = "Mee Goreng",
                            price = 6.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
